# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = "2"
  end
  # Forward Demo Application Port
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provision "file", source: "../requirements.txt", destination: "/home/ubuntu/requirements.txt"
  config.vm.provision "shell", path: "install.sh", privileged: false
  config.vm.synced_folder "./devstack", "/opt/stack", create: true
  config.vm.synced_folder "../src", "/home/ubuntu/flask-app"
end
